### ISSUE TITLE
Resolve exclusion of recommendation 5.3

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/SecOps-Powershell-CISDSC#275]
## Context

**Is your feature request related to a problem? Please describe.**

CIS Recommendation 5.3 - Disabling the 'Computer Browser' service, broke login in our testing.
In the current `main` branch it is excluded. 

**Describe the solution you'd like**

We would prefer to resolve our approach before creating the next tagged release.
For now it, is excluded, as bricking login is an unacceptable outcome for the default configuration.

After follow up with CIS, if this is still a valid recommendation, we would ideally support adding it back in, in some safe manner.

**Describe alternatives you've considered**

It is possible we will take this occasion to add a configuration flag for 'Include unsupported recommendations'.

**Additional context**

This recommendation only caused an issue on the Windows 11 23H2 build. 
It was included, and but did not break login, to our knowledge, in any previous Windows 10 builds.

## Tasks

- [ ] test whether we can replicate the issue on Windows 10
- [ ] reach out to CIS to get more information on the expected use of this recommendation
- [x] document whatever we find in this issue, and open a new issue if follow-up work is determined

**Comment by edthedev** [comment]
Blocks our next tag, because we want to at least know more about this issue before we proceed.

**Comment by baristaTam** [comment]
So I'm still trying to confirm this, but I think I have a best guess as to what's going on with the "configuration breaks netlogon" stuff. 

Context:
Recommendation 5.3 "Ensure Computer Browser (Browser) is set to Disabled or Not Installed" which tracks with Microsoft's statement on it here: https://learn.microsoft.com/en-us/windows/whats-new/deprecated-features

The Computer Browser SERVICE, relies on the bowser.sys DRIVER. The recommendation is for the SERVICE (which doesn't even exist anymore in win 10/11) and the DRIVER needs to stay running. The CIS benchmark GPOkit erroneously disables the DRIVER. 

So I would actually argue this is a case to remove it from the configs. Still confirming all the above is true, however.

**Comment by edthedev** [comment]
Per further investigation, we have confirmed that this is due to a mismatch between the intended recommendation (turn off a deprecated service) and the actual GPO Kit (turns off a similarly named, still relevant service).

@baristaTam  will put in a ticket with CIS requesting a correction.

As a follow-up, we should exclude this from our final definition for Win 11. (And possibly others.)
