### ISSUE TITLE
Document anticipated end of life date

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/SecOps-Powershell-CISDSC#286]
**Is your feature request related to a problem? Please describe.**
Documentation correction.

**Describe the solution you'd like**
Our supported open source products all include a couple of lines in README that shares, based on our expert understanding, a how long (at minimum) we anticipate the product will continue to work without any further changes, based on the update frequency of the technologies it relies on.

**Describe alternatives you've considered**
None. This is mandatory documentation for our supported products.

**Additional context**
This is documentation cleanup for consistency.

## Tasks

- [x] research expected end of life of newest version of PowerShell that we test against (PowerShell 7)
- [x] research expected end of life of the newest configuration set we have added (Windows 11)
- [x] add an 'End of Life' section to README.md, based on the template here: https://answers.uillinois.edu/illinois/109544

**Comment by mpitcel** [comment]
PowerShell 7 Information:
- 7.0 (LTS) End Support Date was 03 Dec 2022 
- 7.2 (LTS) End Support Date is 08 Nov 2024 
- 7.4 (LTS) End Support Date is 10 Nov 2026

Dates from https://endoflife.date/powershell

**Comment by mpitcel** [comment]
Windows 11 Information:
- 11 21H2 (E) End Support Date is 08 Oct 2024 
- 11 22H2 (E) End Support Date is 14 Oct 2025 
- 11 23H2 (E) End Support Date is 10 Nov 2026

Dates from https://endoflife.date/windows

**Comment by mpitcel** [comment]
@edthedev , do you know which exact versions of PowerShell and Windows 11 should be referenced?

**Comment by mpitcel** [comment]
Tentative text to add based upon the latest dates available for PowerShell and Windows 11:

# End-of-Life and End-of-Support Dates

This product is supported by the Cybersecurity teams at the
University of Illinois Urbana-Champaign on a best-effort basis.

As of the last update to this README, the expected End-of-Life
and End-of-Support dates of this product are 10 November 2026.

End-of-Life was decided upon based on these dependencies:

- PowerShell 7.4 (10 November 2026)
- Windows 11 23H2 (10 November 2026)

**Comment by mpitcel** [comment]
PR created
